[workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]
name = "llm-lab"
version = "0.1.0"

[tasks]
train = "python train.py"
dashboard = "streamlit run dashboard.py"

[system-requirements]
cuda = "12.6"

[dependencies]
python = "3.11.*"
pytorch-gpu = ">=2.9.1,<3"
clearml = ">=2.1.2,<3"
jupyterlab = ">=4.5.2,<5"
pandas = ">=2.3.3,<3"
matplotlib = ">=3.10.8,<4"
streamlit = ">=1.53.0,<2"
plotly = ">=6.5.2,<7"
pyyaml = ">=6.0.3,<7"
scikit-learn = ">=1.8.0,<2"
tqdm = ">=4.67.1,<5"
seaborn = ">=0.13.2,<0.14"
