[workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]
name = "gpt-from-scratch"
version = "0.1.0"

[tasks]

[system-requirements]
cuda = "12.6"

[dependencies]
python = "3.11.*"
pytorch-gpu = ">=2.9.1,<3"
clearml = ">=2.1.2,<3"
